version: "3"
services:
  mongo:
    image: mongo
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - mongo-db:/data/db
  node-app:
    build: .
    restart: unless-stopped
    env_file: ./.env
    #ports:
    # - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    depends_on:
      - mongo

volumes:
  mongo-db:
