version: "3"
services:
  node-app:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    restart: always
    environment:
      - PORT=3000
#env_file:
# - ./.env
